"use client"

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Progress } from "@/components/ui/progress"
import { 
  TrendingUp, 
  TrendingDown, 
  Users, 
  Target, 
  Clock, 
  Activity, 
  BarChart3,
  Zap,
  DollarSign,
  Package
} from "lucide-react"
import { useActions, useAppStore, useMetrics, usePredictions } from "@/lib/store"
import { useState, useEffect } from "react"

const formatPredictionType = (type) => {
  if (!type) return "AI Insight"
  return type
    .toString()
    .replace(/[_-]+/g, " ")
    .split(" ")
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ")
}

const getSeverityMeta = (severity) => {
  const value = (severity || "Medium").toString().toLowerCase()
  if (value === "high") {
    return { label: "High", variant: "destructive" }
  }
  if (value === "low") {
    return { label: "Low", variant: "outline" }
  }
  return { label: "Medium", variant: "secondary" }
}

const formatUpdatedTimestamp = (timestamp) => {
  if (!timestamp) return "Just now"
  const parsed = new Date(timestamp)
  if (Number.isNaN(parsed.getTime())) return "Just now"
  return parsed.toLocaleString("en-IN", {
    day: "2-digit",
    month: "short",
    hour: "2-digit",
    minute: "2-digit"
  })
}

const formatImpactValue = (value) => {
  if (value == null) return "Impact pending"
  const numeric = Number(value)
  if (Number.isFinite(numeric)) {
    return new Intl.NumberFormat("en-IN", {
      style: "currency",
      currency: "INR",
      maximumFractionDigits: numeric >= 100000 ? 0 : 1
    }).format(numeric)
  }
  return value
}

const PRODUCT_KEYWORDS = ["inventory", "stock", "sku", "product", "reorder", "supply"]

const isProductRelated = (text = "") => {
  const haystack = text.toLowerCase()
  return PRODUCT_KEYWORDS.some((keyword) => haystack.includes(keyword))
}

const buildActionSuggestion = (action) => ({
  id: action.id,
  title: action.title || formatPredictionType(action.action_type),
  subtitle: action.description || action.generated_content || "AI recommendation awaiting context",
  priority: action.priority || "Medium",
  priorityVariant: action.priority?.toLowerCase() === "high" ? "destructive" : "secondary",
  impactLabel: formatImpactValue(action.expected_impact),
  meta: action.generated_content ? "AI draft ready" : "Requires manual review",
  tone: "amber"
})

const buildInsightSuggestion = (prediction) => ({
  id: prediction.id,
  title: prediction.name || formatPredictionType(prediction.prediction_type),
  subtitle: prediction.description || prediction.recommendation || "Inventory insight generated by ML model",
  priority: `${prediction.severity || "Medium"} Signal`,
  priorityVariant: prediction.severity?.toLowerCase() === "high" ? "destructive" : "secondary",
  impactLabel: prediction.impact || "Review inventory plan",
  meta: prediction.recommendation || "Convert to approval",
  tone: "sky"
})

export function IntelligentDashboard() {
  const actions = useActions()
  const metrics = useMetrics()
  const predictions = usePredictions()
  const { updateMetrics, fetchPredictions, fetchActions } = useAppStore()
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
    Promise.all([updateMetrics(), fetchPredictions(), fetchActions()]).catch(() => {})

    const interval = setInterval(() => {
      Promise.resolve(fetchPredictions()).catch(() => {})
      Promise.resolve(fetchActions()).catch(() => {})
    }, 8000)

    return () => clearInterval(interval)
  }, [updateMetrics, fetchPredictions, fetchActions])

  if (!mounted) {
    return (
      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">
        {[1, 2, 3, 4].map(i => (
          <Card key={i}>
            <CardContent className="p-6">
              <div className="space-y-3">
                <div className="h-4 w-24 skeleton rounded" />
                <div className="h-8 w-16 skeleton rounded" />
                <div className="h-2 w-full skeleton rounded" />
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    )
  }

  const metricCards = [
    {
      title: "Total Customers",
      value: metrics.totalCustomers ?? 0,
      change: Math.max(1, Math.round((metrics.totalCustomers ?? 0) * 0.1)),
      changeType: "increase",
      icon: Users,
      color: "text-blue-600",
      bgColor: "bg-blue-500/10"
    },
    {
      title: "Active Products",
      value: metrics.activeProducts ?? 0,
      change: Math.max(1, Math.round((metrics.activeProducts ?? 0) * 0.15)),
      changeType: "increase",
      icon: Package,
      color: "text-green-600",
      bgColor: "bg-green-500/10"
    },
    {
      title: "Total Revenue",
      value: (() => {
        const revenue = Number(metrics.totalRevenue ?? 0)
        if (revenue >= 100000) {
          return `₹${(revenue / 100000).toFixed(1)}L`
        }
        if (revenue >= 1000) {
          return `₹${(revenue / 1000).toFixed(1)}K`
        }
        return `₹${revenue.toLocaleString('en-IN')}`
      })(),
      change: Math.max(1, Math.round((metrics.totalRevenue ?? 0) / 10000)),
      changeType: "increase",
      icon: DollarSign,
      color: "text-amber-600",
      bgColor: "bg-amber-500/10"
    },
    {
      title: "System Health",
      value: `${Number(metrics.systemHealth ?? 0)}%`,
      change: (metrics.confidenceScore ?? 0) - 85,
      changeType: (metrics.confidenceScore ?? 0) > 85 ? "increase" : "decrease",
      icon: Activity,
      color: (metrics.systemHealth ?? 0) > 80 ? "text-green-600" : "text-red-600",
      bgColor: (metrics.systemHealth ?? 0) > 80 ? "bg-green-500/10" : "bg-red-500/10"
    }
  ]

  const recentInsights = [...predictions]
    .sort(
      (a, b) =>
        new Date(b.createdAt ?? b.created_at) - new Date(a.createdAt ?? a.created_at)
    )
    .slice(0, 3)
  const pendingActions = actions.filter((action) => action.status === "pending")
  const productPendingActions = pendingActions
    .filter((action) => isProductRelated(`${action.action_type} ${action.title} ${action.description}`))
    .slice(0, 3)
  const inventorySignals = predictions
    .filter((prediction) => isProductRelated(`${prediction.prediction_type} ${prediction.name}`))
    .slice(0, 3)
  const productSuggestions = productPendingActions.length
    ? productPendingActions.map(buildActionSuggestion)
    : inventorySignals.map(buildInsightSuggestion)
  const hasSuggestions = productSuggestions.length > 0

  return (
    <div className="space-y-6">
      {/* Key Metrics */}
      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">
        {metricCards.map((metric, index) => {
          const Icon = metric.icon
          return (
            <Card key={index}>
              <CardContent className="p-6">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm font-medium text-muted-foreground">
                      {metric.title}
                    </p>
                    <p className="text-2xl font-bold">{metric.value}</p>
                  </div>
                  <div className={`flex size-8 items-center justify-center rounded-lg ${metric.bgColor}`}>
                    <Icon className={`size-4 ${metric.color}`} />
                  </div>
                </div>
                <div className="mt-4 flex items-center gap-2">
                  {metric.changeType === "increase" ? (
                    <TrendingUp className="size-4 text-green-600" />
                  ) : (
                    <TrendingDown className="size-4 text-red-600" />
                  )}
                  <span className={`text-sm ${
                    metric.changeType === "increase" ? "text-green-600" : "text-red-600"
                  }`}>
                    {metric.changeType === "increase" ? "+" : ""}{metric.change}
                  </span>
                  <span className="text-sm text-muted-foreground">
                    from last period
                  </span>
                </div>
              </CardContent>
            </Card>
          )
        })}
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        {/* Recent AI Insights */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Zap className="size-5 text-primary" />
              Recent AI Insights
            </CardTitle>
            <CardDescription>
              Latest intelligence from the AI engine
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {recentInsights.length === 0 ? (
                <div className="py-8 text-center text-sm text-muted-foreground">
                  <Activity className="size-12 mx-auto mb-4 opacity-50" />
                  <p>Waiting for backend predictions...</p>
                </div>
              ) : (
                recentInsights.map((insight) => {
                  const severityMeta = getSeverityMeta(insight.severity)
                  const title = insight.name || formatPredictionType(insight.type || insight.prediction_type)
                  const confidenceLabel = Number.isFinite(insight.confidence)
                    ? `${insight.confidence}% confident`
                    : "Confidence pending"

                  return (
                    <div key={insight.id} className="flex items-start gap-3 p-3 rounded-lg border">
                      <div className="flex size-8 shrink-0 items-center justify-center rounded-lg bg-primary/10">
                        <Target className="size-4 text-primary" />
                      </div>
                      <div className="flex-1 space-y-1">
                        <p className="font-medium text-sm">{title}</p>
                        <p className="text-xs text-muted-foreground line-clamp-2">
                          {insight.description || "No description available."}
                        </p>
                        <div className="flex flex-wrap items-center gap-2">
                          <Badge variant="outline" className="text-xs">
                            {confidenceLabel}
                          </Badge>
                          <Badge variant={severityMeta.variant} className="text-xs capitalize">
                            {severityMeta.label}
                          </Badge>
                          <span className="text-xs text-muted-foreground">
                            Updated {formatUpdatedTimestamp(insight.createdAt ?? insight.created_at)}
                          </span>
                        </div>
                      </div>
                    </div>
                  )
                })
              )}
            </div>
          </CardContent>
        </Card>

        {/* Pending Actions */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Clock className="size-5 text-amber-500" />
              Pending Actions
            </CardTitle>
            <CardDescription>
              Product-level recommendations awaiting approval
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {!hasSuggestions ? (
                <div className="py-8 text-center text-sm text-muted-foreground">
                  <Target className="size-12 mx-auto mb-4 opacity-50" />
                  <p>No product approvals required right now</p>
                </div>
              ) : (
                productSuggestions.map((suggestion) => (
                  <div key={suggestion.id} className="flex items-start gap-3 rounded-lg border p-3">
                    <div
                      className={`flex size-8 shrink-0 items-center justify-center rounded-lg ${
                        suggestion.tone === "amber" ? "bg-amber-500/10" : "bg-sky-500/10"
                      }`}
                    >
                      <Activity
                        className={`size-4 ${
                          suggestion.tone === "amber" ? "text-amber-500" : "text-sky-500"
                        }`}
                      />
                    </div>
                    <div className="flex-1 space-y-1">
                      <p className="font-medium text-sm">{suggestion.title}</p>
                      <p className="text-xs text-muted-foreground line-clamp-2">
                        {suggestion.subtitle}
                      </p>
                      <div className="flex flex-wrap items-center gap-2 text-xs">
                        <Badge variant={suggestion.priorityVariant} className="text-xs">
                          {suggestion.priority}
                        </Badge>
                        <span className="text-muted-foreground">{suggestion.impactLabel}</span>
                        <span className="text-muted-foreground/80">{suggestion.meta}</span>
                      </div>
                    </div>
                  </div>
                ))
              )}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* System Performance */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <BarChart3 className="size-5 text-primary" />
            System Performance
          </CardTitle>
          <CardDescription>
            Real-time AI system metrics and efficiency
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid gap-6 md:grid-cols-3">
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-sm font-medium">Time Saved</span>
                <span className="text-sm text-muted-foreground">
                  {Number(metrics.timeSaved).toFixed(1)} hours
                </span>
              </div>
              <Progress value={Math.min(100, Number(metrics.timeSaved) * 2)} className="h-2" />
            </div>
            
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-sm font-medium">Actions Executed</span>
                <span className="text-sm text-muted-foreground">
                  {metrics.executedActions ?? 0}
                </span>
              </div>
              <Progress 
                value={(() => {
                  const executed = metrics.executedActions ?? 0
                  const pending = metrics.pendingActions ?? 0
                  const total = Math.max(1, executed + pending)
                  return Math.min(100, (executed / total) * 100)
                })()} 
                className="h-2" 
              />
            </div>
            
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-sm font-medium">AI Confidence</span>
                <span className="text-sm text-muted-foreground">
                  {metrics.confidenceScore ?? 0}%
                </span>
              </div>
              <Progress value={metrics.confidenceScore ?? 0} className="h-2" />
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
